name: Checks

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/workflows/publish.yml"
  pull_request:
    paths-ignore:
      - ".github/workflows/publish.yml"

jobs:
  build_mod:
    uses: ./.github/workflows/build-mod.yml
    secrets:
      unity_license: ${{ secrets.UNITY_LICENSE }}
      unity_email: ${{ secrets.UNITY_EMAIL }}
      unity_password: ${{ secrets.UNITY_PASSWORD }}
